
export const SET_ACTIVE_BOTTOM_NAVIGATION = "SET_ACTIVE_BOTTOM_NAVIGATION";
export const SET_ALL_RECIPES = "SET_ALL_RECIPES";
export const SET_FAVORITE_RECIPES = "SET_FAVORITE_RECIPES";
export const RESET_RECIPES = "RESET_RECIPES";
