const cardMock = [
  {
    itemId: '5dfba99ebc737b4330e6ecbb',
    avatarName: 'ML',
    title: 'Georgina Simpson',
    date: '2019-08-11T05:31:38 -02:00',
    description: 'Occaecat deserunt consequat exercitation exercitation elit ex occaecat aute adipisicing. Tempor laboris ex id officia non veniam reprehenderit dolor aliqua velit id. Qui sunt adipisicing exercitation amet sit.\r\n',
    imgUrl: 'https://picsum.photos/300/200',
  },
  {
    itemId: '5dfba99e2d8220c2bda1bd9c',
    avatarName: 'ML',
    title: 'Erin Cleveland',
    date: '2016-05-17T12:32:02 -02:00',
    description: 'Cupidatat excepteur fugiat pariatur ipsum mollit et qui nisi consequat minim esse elit officia. Duis sit cupidatat duis consectetur consequat est incididunt pariatur dolor excepteur anim consectetur cillum. Labore sint fugiat et excepteur exercitation id qui commodo magna elit ullamco esse occaecat. Sunt officia adipisicing in adipisicing. Enim Lorem aute non ea et aliquip sunt occaecat pariatur nostrud eiusmod esse nostrud excepteur. Pariatur cupidatat laborum consectetur dolore Lorem occaecat adipisicing dolor nulla commodo ut. Deserunt magna esse aliqua reprehenderit consequat aliquip.\r\n',
    imgUrl: 'https://picsum.photos/300/200',
  },
  {
    itemId: '5dfba99ee06c17f17855bfcc',
    avatarName: 'ML',
    title: 'Gregory Gray',
    date: '2017-08-02T07:49:33 -02:00',
    description: 'Excepteur Lorem aute occaecat aliquip excepteur enim anim ad ad pariatur. Minim fugiat Lorem elit adipisicing anim minim. Et consectetur est sunt reprehenderit do deserunt eiusmod do laboris ipsum mollit proident culpa. Dolor velit ea voluptate deserunt.\r\n',
    imgUrl: 'https://picsum.photos/300/200',
  },
  {
    itemId: '5dfba99ece1c187c8365ee48',
    avatarName: 'ML',
    title: 'Angelia Sosa',
    date: '2017-06-09T11:39:47 -02:00',
    description: 'Qui adipisicing sunt labore amet non incididunt dolor ut eu labore ea tempor magna. Nostrud ex nulla pariatur commodo culpa nisi labore nisi. Ea adipisicing id exercitation labore aute dolore ipsum eiusmod exercitation eiusmod consequat nulla in eiusmod. Voluptate ipsum elit proident irure est. Culpa nulla ut fugiat anim commodo dolore dolore ex laborum consectetur magna mollit ullamco.\r\n',
    imgUrl: 'https://picsum.photos/300/200',
  },
  {
    itemId: '5dfba99e3e2a8612adf9547f',
    avatarName: 'ML',
    title: 'Ryan Holt',
    date: '2019-03-28T04:48:03 -01:00',
    description: 'Reprehenderit esse duis in irure duis proident reprehenderit amet ex consequat proident non. Ullamco occaecat quis tempor reprehenderit veniam laboris. Lorem qui ipsum nisi voluptate ea tempor irure quis nulla. Eiusmod est consequat eiusmod aliqua ea.\r\n',
    imgUrl: 'https://picsum.photos/300/200',
  },
  {
    itemId: '5dfba99e40e17110188290dc',
    avatarName: 'ML',
    title: 'Holman Leach',
    date: '2014-10-08T08:12:18 -02:00',
    description: 'Voluptate nulla amet fugiat tempor voluptate veniam sit non est ipsum. Culpa consectetur eiusmod velit nisi est esse cillum ullamco irure sint elit. Veniam aute et nulla excepteur nostrud sunt dolore sit occaecat. Amet enim Lorem consectetur velit duis eiusmod ex cupidatat. Deserunt anim sint eu amet aute laboris deserunt.\r\n',
    imgUrl: 'https://picsum.photos/300/200',
  },
  {
    itemId: '5dfba99edda4653f4876be5c',
    avatarName: 'ML',
    title: 'Head Leon',
    date: '2017-01-01T10:47:04 -01:00',
    description: 'Adipisicing amet labore aute dolore labore culpa Lorem qui exercitation. Fugiat sit nulla qui pariatur qui aliqua. Proident esse nulla laboris adipisicing incididunt id dolor consequat anim enim veniam ipsum. Cillum ut cupidatat ipsum tempor aliquip pariatur aute. Ipsum dolor proident elit veniam sunt nisi esse et enim nisi. Esse minim exercitation consectetur veniam in minim qui et proident occaecat amet adipisicing.\r\n',
    imgUrl: 'https://picsum.photos/300/200',
  },
  {
    itemId: '5dfba99edda4653f4faf876be5c',
    avatarName: 'ML',
    title: 'Head Leon',
    date: '2017-01-01T10:47:04 -01:00',
    description: 'Adipisicing amet labore aute dolore labore culpa Lorem qui exercitation. Fugiat sit nulla qui pariatur qui aliqua. Proident esse nulla laboris adipisicing incididunt id dolor consequat anim enim veniam ipsum. Cillum ut cupidatat ipsum tempor aliquip pariatur aute. Ipsum dolor proident elit veniam sunt nisi esse et enim nisi. Esse minim exercitation consectetur veniam in minim qui et proident occaecat amet adipisicing.\r\n',
    imgUrl: 'https://picsum.photos/300/200',
  },
];

export default cardMock;
